REM !!! DO NOT EDIT THIS FILE !!!
REM GENERATED BY DATA FACTORY GENERATOR

SET SCRIPT_DIR=%~dp0
SET ENV_DIR=%SCRIPT_DIR%\environments\docker-desktop

REM ingress-controller NGINX
kubectl.exe apply -f %ENV_DIR%\kubernetes\ingress-nginx\ingress-nginx.yaml
kubectl.exe wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=300s

REM ArgoCD 
kubectl.exe apply -f %ENV_DIR%\kubernetes\docker-desktop\default\argocd
kubectl.exe apply -f %ENV_DIR%\kubernetes\docker-desktop\argocd-namespace.yaml
kubectl.exe apply -f %ENV_DIR%\kubernetes\docker-desktop\argocd\

REM end of file