apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bytefusion-data-platform
  namespace: tekton-pipelines
spec:
  params:
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/bfblog/bytefusion-cloud-platform
        - name: revision
          value: work
      workspaces:
        - name: output
          workspace: source
    - name: buildah-fluentd
      taskRef:
        name: buildah
      params:
        - name: CONTEXT
          value: docker/fluentd
        - name: IMAGE
          value: docker-registry:5000/bfblog/fluentd:latest
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: source
    - name: buildah-shell
      taskRef:
        name: buildah
      params:
        - name: CONTEXT
          value: docker/shell
        - name: IMAGE
          value: docker-registry:5000/bfblog/data-factory-shell:latest
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: source
  workspaces:
  - name: source
    description: The folder where we write the message to
    
        

