kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bytefusion-cloud-platform-workspace
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
