apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: tekton-pipelines
spec:
  ca:
    secretName: certs-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: tekton-pipelines
spec:
  selfSigned: {}