# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ work, master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Build Date
      id: shell
      run: |
        echo "::set-output name=date::$(date --iso-8601=seconds)"

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
      
    - name: Commit Revision
      run: echo running on commit-rev ${GITHUB_SHA##*/}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{ steps.shell.outputs.date }}
        echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#          java-version: 1.8
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    
    - name: Build Docker image
      run: |
        docker build \
          --tag bfblog/fluentd:latest \
          --tag bfblog/fluentd:${GITHUB_SHA::8} \
          --label org.opencontainers.image.created=${{ steps.shell.outputs.date }} \
          --label org.opencontainers.image.authors="Markus Breuer" \
          --label org.opencontainers.image.url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          --label org.opencontainers.image.revision=${GITHUB_SHA##*/} \
          --label org.opencontainers.image.title=fluentd \
          --label org.opencontainers.image.description= \
          --label org.opencontainers.image.base.digest= \
          --label org.opencontainers.image.vendor=www.bytefusion.de \
          --label org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          --label org.opencontainers.image.documentation="-" \
          docker/fluentd
      
#    - uses: azure/container-scan@v0
#      with:
#        image-name: bfblog/fluentd:latest
    
    - name: Publish Docker image
      run: docker push bfblog/fluentd:latest 

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Build Date
      id: shell
      run: |
        echo "::set-output name=date::$(date --iso-8601=seconds)"

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
      
    - name: Commit Revision
      run: echo running on commit-rev ${GITHUB_SHA##*/}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{ steps.shell.outputs.date }}
        echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    
    - name: Build Docker image
      run: |
        docker build \
          --tag bfblog/data-factory-shell:latest \
          --tag bfblog/data-factory-shell:${GITHUB_SHA::8} \
          --label org.opencontainers.image.created=${{ steps.shell.outputs.date }} \
          --label org.opencontainers.image.authors="Markus Breuer" \
          --label org.opencontainers.image.url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          --label org.opencontainers.image.revision=${GITHUB_SHA##*/} \
          --label org.opencontainers.image.title=data factory shell \
          --label org.opencontainers.image.description= \
          --label org.opencontainers.image.base.digest= \
          --label org.opencontainers.image.vendor=www.bytefusion.de \
          --label org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          --label org.opencontainers.image.documentation="-" \
          docker/shell
    
    - name: Publish Docker image
      run: docker push bfblog/data-factory-shell:latest 
